-- MySQL Script generated by MySQL Workbench
-- Sun Oct 16 01:11:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Assignment1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Assignment1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Assignment1` DEFAULT CHARACTER SET utf8 ;
USE `Assignment1` ;

-- -----------------------------------------------------
-- Table `Assignment1`.` ENROLLMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.` ENROLLMENT` (
  `EnrollmentId` INT NOT NULL,
  `DateEnrolled` DATE NOT NULL,
  `DateUnenrolled` DATE NOT NULL,
  `AcademicYear` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`EnrollmentId`),
  UNIQUE INDEX `EnrollmentId_UNIQUE` (`EnrollmentId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`STUDENT` (
  `Student Id` INT NOT NULL,
  `StudentName` VARCHAR(30) NOT NULL,
  `StudentBirthday` DATE NOT NULL,
  `StudentGender` VARCHAR(10) NOT NULL,
  `Student Address` VARCHAR(50) NOT NULL,
  `Enrollment_EnrollmentId` INT NOT NULL,
  PRIMARY KEY (`Student Id`, `Enrollment_EnrollmentId`),
  INDEX `fk_Stuent_ Enrollment1_idx` (`Enrollment_EnrollmentId` ASC) VISIBLE,
  UNIQUE INDEX `Student Id_UNIQUE` (`Student Id` ASC) VISIBLE,
  UNIQUE INDEX `Enrollment_EnrollmentId_UNIQUE` (`Enrollment_EnrollmentId` ASC) VISIBLE,
  CONSTRAINT `fk_Stuent_ Enrollment1`
    FOREIGN KEY (`Enrollment_EnrollmentId`)
    REFERENCES `Assignment1`.` ENROLLMENT` (`EnrollmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`GUARDIAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`GUARDIAN` (
  `Guardian Id` INT NOT NULL,
  `GuardianName` VARCHAR(30) NOT NULL,
  `Guardian Address` VARCHAR(50) NOT NULL,
  `GuardianBirtday` DATE NOT NULL,
  `GuardianGender` VARCHAR(10) NOT NULL,
  `GuardianPhone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Guardian Id`),
  UNIQUE INDEX `Guardian Id_UNIQUE` (`Guardian Id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`STUDENT_has_GUARDIAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`STUDENT_has_GUARDIAN` (
  `STUDENT_StudentId` INT NOT NULL,
  `GUARDIAN_GuardianId` INT NOT NULL,
  PRIMARY KEY (`STUDENT_StudentId`, `GUARDIAN_GuardianId`),
  INDEX `fk_Stuent_has_Guardian_Guardian1_idx` (`GUARDIAN_GuardianId` ASC) VISIBLE,
  INDEX `fk_Stuent_has_Guardian_Stuent_idx` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `STUDENT_StudentId_UNIQUE` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `GUARDIAN_GuardianId_UNIQUE` (`GUARDIAN_GuardianId` ASC) VISIBLE,
  CONSTRAINT `fk_Stuent_has_Guardian_Stuent`
    FOREIGN KEY (`STUDENT_StudentId`)
    REFERENCES `Assignment1`.`STUDENT` (`Student Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stuent_has_Guardian_Guardian1`
    FOREIGN KEY (`GUARDIAN_GuardianId`)
    REFERENCES `Assignment1`.`GUARDIAN` (`Guardian Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.` DISCIPLINARY_ACTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.` DISCIPLINARY_ACTION` (
  ` DisciplinaryActionsId` INT NOT NULL,
  `IncidentType` VARCHAR(30) NOT NULL,
  PRIMARY KEY (` DisciplinaryActionsId`),
  UNIQUE INDEX ` DisciplinaryActionsId_UNIQUE` (` DisciplinaryActionsId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`DISCIPLINARYACTION_ON_STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`DISCIPLINARYACTION_ON_STUDENT` (
  `DisciplinaryActions_ Disciplinary Actions Id` INT NOT NULL,
  `STUDENT_StudentId` INT NOT NULL,
  `IncidentDate` DATE NOT NULL,
  `DisciplinaryActionTaken` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`DisciplinaryActions_ Disciplinary Actions Id`, `STUDENT_StudentId`),
  INDEX `fk_ Disciplinary Actions_has_Stuent_Stuent1_idx` (`STUDENT_StudentId` ASC) VISIBLE,
  INDEX `fk_ Disciplinary Actions_has_Stuent_ Disciplinary Actions1_idx` (`DisciplinaryActions_ Disciplinary Actions Id` ASC) VISIBLE,
  UNIQUE INDEX `DisciplinaryActions_ Disciplinary Actions Id_UNIQUE` (`DisciplinaryActions_ Disciplinary Actions Id` ASC) VISIBLE,
  UNIQUE INDEX `STUDENT_StudentId_UNIQUE` (`STUDENT_StudentId` ASC) VISIBLE,
  CONSTRAINT `fk_ Disciplinary Actions_has_Stuent_ Disciplinary Actions1`
    FOREIGN KEY (`DisciplinaryActions_ Disciplinary Actions Id`)
    REFERENCES `Assignment1`.` DISCIPLINARY_ACTION` (` DisciplinaryActionsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ Disciplinary Actions_has_Stuent_Stuent1`
    FOREIGN KEY (`STUDENT_StudentId`)
    REFERENCES `Assignment1`.`STUDENT` (`Student Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`TEST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`TEST` (
  `TEST Id` INT NOT NULL,
  `TestName` VARCHAR(30) NOT NULL,
  `TestDate` DATE NOT NULL,
  `TestResult` VARCHAR(10) NOT NULL,
  `Student_Id` INT NOT NULL,
  PRIMARY KEY (`TEST Id`, `Student_Id`),
  UNIQUE INDEX `TEST Id_UNIQUE` (`TEST Id` ASC) VISIBLE,
  UNIQUE INDEX `Student_Id_UNIQUE` (`Student_Id` ASC) VISIBLE,
  CONSTRAINT `Student_Id`
    FOREIGN KEY (`Student_Id`)
    REFERENCES `Assignment1`.`STUDENT` (`Student Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`CLUB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`CLUB` (
  `ClubId` INT NOT NULL,
  `ClubName` VARCHAR(50) NOT NULL,
  `AcademicYear` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ClubId`),
  UNIQUE INDEX `ClubId_UNIQUE` (`ClubId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`HIGH_SCHOOL_EDUCATION_PLAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`HIGH_SCHOOL_EDUCATION_PLAN` (
  `HighSchoolEducationPlanId` INT NOT NULL,
  `EducationId` INT NOT NULL,
  `EducationName` VARCHAR(50) NOT NULL,
  `ApplicationResult` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`HighSchoolEducationPlanId`),
  UNIQUE INDEX `HighSchoolEducationPlanId_UNIQUE` (`HighSchoolEducationPlanId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`HOMEROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`HOMEROOM` (
  `HomeromeId` INT NOT NULL,
  `HomeroomTeacher` VARCHAR(30) NOT NULL,
  `HomeroomLocation` VARCHAR(50) NOT NULL,
  `ENROLLMENT_EnrollmentId` INT NOT NULL,
  PRIMARY KEY (`HomeromeId`, `ENROLLMENT_EnrollmentId`),
  INDEX `fk_Home Room_ Enrollment1_idx` (`ENROLLMENT_EnrollmentId` ASC) VISIBLE,
  UNIQUE INDEX `HomeromeId_UNIQUE` (`HomeromeId` ASC) VISIBLE,
  UNIQUE INDEX `ENROLLMENT_EnrollmentId_UNIQUE` (`ENROLLMENT_EnrollmentId` ASC) VISIBLE,
  CONSTRAINT `fk_Home Room_ Enrollment1`
    FOREIGN KEY (`ENROLLMENT_EnrollmentId`)
    REFERENCES `Assignment1`.` ENROLLMENT` (`EnrollmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`COURSE` (
  `CourseId` INT NOT NULL,
  `CoursesName` VARCHAR(30) NOT NULL,
  `CourseLocation` VARCHAR(30) NOT NULL,
  `ENROLLMENT_EnrollmentId` INT NOT NULL,
  PRIMARY KEY (`CourseId`, `ENROLLMENT_EnrollmentId`),
  INDEX `fk_Course_ Enrollment1_idx` (`ENROLLMENT_EnrollmentId` ASC) VISIBLE,
  UNIQUE INDEX `CourseId_UNIQUE` (`CourseId` ASC) VISIBLE,
  UNIQUE INDEX `ENROLLMENT_EnrollmentId_UNIQUE` (`ENROLLMENT_EnrollmentId` ASC) VISIBLE,
  CONSTRAINT `fk_Course_ Enrollment1`
    FOREIGN KEY (`ENROLLMENT_EnrollmentId`)
    REFERENCES `Assignment1`.` ENROLLMENT` (`EnrollmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`PERIOD_GPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`PERIOD_GPA` (
  `PeriodGPAId` INT NOT NULL,
  `COURSE_CourseId` INT NOT NULL,
  `COURSE_ENROLLMENT_EnrollmentId` INT NOT NULL,
  `PeriodGPAResult` DECIMAL NOT NULL,
  PRIMARY KEY (`PeriodGPAId`),
  INDEX `fk_PERIOD_GPA_COURSE1_idx` (`COURSE_CourseId` ASC, `COURSE_ENROLLMENT_EnrollmentId` ASC) VISIBLE,
  UNIQUE INDEX `PeriodGPAId_UNIQUE` (`PeriodGPAId` ASC) VISIBLE,
  CONSTRAINT `fk_PERIOD_GPA_COURSE1`
    FOREIGN KEY (`COURSE_CourseId` , `COURSE_ENROLLMENT_EnrollmentId`)
    REFERENCES `Assignment1`.`COURSE` (`CourseId` , `ENROLLMENT_EnrollmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`YEAR_GPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`YEAR_GPA` (
  `YearGPAId` INT NOT NULL,
  `COURSE_CourseId` INT NOT NULL,
  `COURSE_ENROLLMENT_EnrollmentId` INT NOT NULL,
  `YearGPAReult` DECIMAL NOT NULL,
  PRIMARY KEY (`YearGPAId`),
  INDEX `fk_YEAR_GPA_COURSE1_idx` (`COURSE_CourseId` ASC, `COURSE_ENROLLMENT_EnrollmentId` ASC) VISIBLE,
  UNIQUE INDEX `YearGPAId_UNIQUE` (`YearGPAId` ASC) VISIBLE,
  CONSTRAINT `fk_YEAR_GPA_COURSE1`
    FOREIGN KEY (`COURSE_CourseId` , `COURSE_ENROLLMENT_EnrollmentId`)
    REFERENCES `Assignment1`.`COURSE` (`CourseId` , `ENROLLMENT_EnrollmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`OVERALL_GPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`OVERALL_GPA` (
  `OverallGPAId` INT NOT NULL,
  `COURSE_CourseId` INT NOT NULL,
  `COURSE_ENROLLMENT_EnrollmentId` INT NOT NULL,
  `YearGPAResult` DECIMAL NOT NULL,
  PRIMARY KEY (`OverallGPAId`),
  INDEX `fk_OVERALL_GPA_COURSE1_idx` (`COURSE_CourseId` ASC, `COURSE_ENROLLMENT_EnrollmentId` ASC) VISIBLE,
  UNIQUE INDEX `OverallGPAId_UNIQUE` (`OverallGPAId` ASC) VISIBLE,
  CONSTRAINT `fk_OVERALL_GPA_COURSE1`
    FOREIGN KEY (`COURSE_CourseId` , `COURSE_ENROLLMENT_EnrollmentId`)
    REFERENCES `Assignment1`.`COURSE` (`CourseId` , `ENROLLMENT_EnrollmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`STUDENT_has_CLUB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`STUDENT_has_CLUB` (
  `STUDENT_StudentId` INT NOT NULL,
  `CLUB_ClubId` INT NOT NULL,
  `StudentClubPostion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`STUDENT_StudentId`, `CLUB_ClubId`),
  INDEX `fk_Stuent_has_Club_Club1_idx` (`CLUB_ClubId` ASC) VISIBLE,
  INDEX `fk_Stuent_has_Club_Stuent1_idx` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `STUDENT_StudentId_UNIQUE` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `CLUB_ClubId_UNIQUE` (`CLUB_ClubId` ASC) VISIBLE,
  CONSTRAINT `fk_Stuent_has_Club_Stuent1`
    FOREIGN KEY (`STUDENT_StudentId`)
    REFERENCES `Assignment1`.`STUDENT` (`Student Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stuent_has_Club_Club1`
    FOREIGN KEY (`CLUB_ClubId`)
    REFERENCES `Assignment1`.`CLUB` (`ClubId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`STUDENT_has_COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`STUDENT_has_COURSE` (
  `STUDENT_StudentId` INT NOT NULL,
  `COURCE_CourseId` INT NOT NULL,
  `Cource_Grade` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`STUDENT_StudentId`, `COURCE_CourseId`),
  INDEX `fk_Stuent_has_Course_Course1_idx` (`COURCE_CourseId` ASC) VISIBLE,
  INDEX `fk_Stuent_has_Course_Stuent1_idx` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `STUDENT_StudentId_UNIQUE` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `COURCE_CourseId_UNIQUE` (`COURCE_CourseId` ASC) VISIBLE,
  CONSTRAINT `fk_Stuent_has_Course_Stuent1`
    FOREIGN KEY (`STUDENT_StudentId`)
    REFERENCES `Assignment1`.`STUDENT` (`Student Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stuent_has_Course_Course1`
    FOREIGN KEY (`COURCE_CourseId`)
    REFERENCES `Assignment1`.`COURSE` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Assignment1`.`STUDENT_has_HIGH_SCHOOL_EDUCATION_PLAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Assignment1`.`STUDENT_has_HIGH_SCHOOL_EDUCATION_PLAN` (
  `STUDENT_StudentId` INT NOT NULL,
  `HIGH_SCHOOL_EDUCATION_PLAN_HighSchoolEducationPlan Id` INT NOT NULL,
  `FinalResult` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`STUDENT_StudentId`, `HIGH_SCHOOL_EDUCATION_PLAN_HighSchoolEducationPlan Id`),
  INDEX `fk_STUDENT_has_HIGH_SCHOOL_EDUCATION_PLAN_HIGH_SCHOOL_EDUCA_idx` (`HIGH_SCHOOL_EDUCATION_PLAN_HighSchoolEducationPlan Id` ASC) VISIBLE,
  INDEX `fk_STUDENT_has_HIGH_SCHOOL_EDUCATION_PLAN_STUDENT1_idx` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `STUDENT_StudentId_UNIQUE` (`STUDENT_StudentId` ASC) VISIBLE,
  UNIQUE INDEX `HIGH_SCHOOL_EDUCATION_PLAN_HighSchoolEducationPlan Id_UNIQUE` (`HIGH_SCHOOL_EDUCATION_PLAN_HighSchoolEducationPlan Id` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_has_HIGH_SCHOOL_EDUCATION_PLAN_STUDENT1`
    FOREIGN KEY (`STUDENT_StudentId`)
    REFERENCES `Assignment1`.`STUDENT` (`Student Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_has_HIGH_SCHOOL_EDUCATION_PLAN_HIGH_SCHOOL_EDUCATI1`
    FOREIGN KEY (`HIGH_SCHOOL_EDUCATION_PLAN_HighSchoolEducationPlan Id`)
    REFERENCES `Assignment1`.`HIGH_SCHOOL_EDUCATION_PLAN` (`HighSchoolEducationPlanId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
